### ISSUE TITLE
搭建完后，新建一篇文章出现bug

### ISSUE THREAD

**Issue by geektcp** [the5fire/django_selfblog#8]
下面的操作都是按照git的安装步骤来搞的。
但是基本功能都用不了，要不是代码有bug，要不就是安装文档有疏漏。

在centOS6.5 64bit(Python 2.6.6)系统上搭建完成后
打开如下链接：
http://10.10.10.111:8000/xadmin
进入后台增加一篇博客，这一步骤没问题

但是再进入
http://10.10.10.111:8000/

点击对应博客后面的 阅读全文 这个超链接
就链接到下面这个不能打开的地址：
http://10.10.10.111:8000/.html

这个东西不是缓存，用chrom按F12看了对应实际链接就这个。
查看了对应的日志文件，还有启动后台没有任何报错。

然后我在centOS7.0  64bit(Python 2.7.57) 也试过，还是这个问题。

**Comment by the5fire** [comment]
你没设置英文标题，那个算是程序设计的问题吧。英文标题不是必填的。比如我的文章：http://www.the5fire.com/do-you-know-about-your-living-env.html  html之前的一串就是英文标题。

**Comment by the5fire** [comment]
done

**Comment by geektcp** [comment]
OK
